# Generated by Django 4.2.1 on 2023-06-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_created_by'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
