# Generated by Django 4.1.9 on 2023-06-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user',
            name='username',
            field=models.CharField(default=' ', max_length=256),
        ),
    ]
