# Generated by Django 4.1.9 on 2023-07-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='probability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
