# Generated by Django 4.1.9 on 2023-06-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
    ]
