# Generated by Django 4.2.1 on 2023-06-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantityFoundInDatabase',
            new_name='outOfStock',
        ),
    ]
