# Generated by Django 4.2.1 on 2023-06-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_created_at_product_modified_at'),
        ('orders', '0003_rename_quantityfoundindatabase_orderitem_outofstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
