# Generated by Django 4.2.1 on 2023-06-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='productName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
