# Generated by Django 4.2.1 on 2023-06-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='addedManually',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='probability',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updatedManually',
            field=models.BooleanField(default=False),
        ),
    ]
