# Generated by Django 4.1.9 on 2023-06-27 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_addedmanually_orderitem_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 27, 9, 17, 40, 724058)),
            preserve_default=False,
        ),
    ]
